[package]
name = "quantum_pixel"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "quantum_pixel"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.28.1"
stegano-core = "0.6.1"
